name: esp32
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    name: Test compile examples for esp32
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout Arduino-List
      uses: actions/checkout@v4
      with:
        repository: davidchatting/Arduino-List
        ref: master
        path: CustomListLib

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@master
      with:
        arduino-board-fqbn: esp32:esp32:esp32
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        arduino-platform: esp32:esp32
        extra-arduino-cli-args: "--warnings default"
        required-libraries: ArduinoJson,StreamUtils,PubSubClient,AceButton
